/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 73.0.5
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// SpaceSchemaAPIService SpaceSchemaAPI service
type SpaceSchemaAPIService service

type ApiListEntityPathsRequest struct {
	ctx        context.Context
	ApiService *SpaceSchemaAPIService
	spaceId    string
	pagination *PaginationInput
	search     *string
}

// Pagination params. Defaults to count 200.  This parameter exists in alpha.
func (r ApiListEntityPathsRequest) Pagination(
	pagination PaginationInput,
) ApiListEntityPathsRequest {
	r.pagination = &pagination
	return r
}

// Filter paths by entity name or path name.  This parameter exists in alpha.
func (r ApiListEntityPathsRequest) Search(search string) ApiListEntityPathsRequest {
	r.search = &search
	return r
}

func (r ApiListEntityPathsRequest) Execute() (*ListEntityPaths200Response, *http.Response, error) {
	return r.ApiService.ListEntityPathsExecute(r)
}

/*
ListEntityPaths List Entity Paths

Returns a list of Entity Paths for a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@return ApiListEntityPathsRequest
*/
func (a *SpaceSchemaAPIService) ListEntityPaths(
	ctx context.Context,
	spaceId string,
) ApiListEntityPathsRequest {
	return ApiListEntityPathsRequest{
		ApiService: a,
		ctx:        ctx,
		spaceId:    spaceId,
	}
}

// Execute executes the request
//
//	@return ListEntityPaths200Response
func (a *SpaceSchemaAPIService) ListEntityPathsExecute(
	r ApiListEntityPathsRequest,
) (*ListEntityPaths200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListEntityPaths200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListEntityPaths",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/entity-paths"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.pagination != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination", r.pagination, "")
	}
	if r.search != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search", r.search, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListEventsRequest struct {
	ctx        context.Context
	ApiService *SpaceSchemaAPIService
	spaceId    string
	pagination *PaginationInput
	sortBy     *string
	sortDir    *string
	search     *string
}

// Pagination params. Defaults to count 200.  This parameter exists in alpha.
func (r ApiListEventsRequest) Pagination(pagination PaginationInput) ApiListEventsRequest {
	r.pagination = &pagination
	return r
}

// Field to sort by. Defaults to &#39;lastSeenAt&#39;.  This parameter exists in alpha.
func (r ApiListEventsRequest) SortBy(sortBy string) ApiListEventsRequest {
	r.sortBy = &sortBy
	return r
}

// Sort direction. Defaults to &#39;desc&#39;.  This parameter exists in alpha.
func (r ApiListEventsRequest) SortDir(sortDir string) ApiListEventsRequest {
	r.sortDir = &sortDir
	return r
}

// Filter events by name substring.  This parameter exists in alpha.
func (r ApiListEventsRequest) Search(search string) ApiListEventsRequest {
	r.search = &search
	return r
}

func (r ApiListEventsRequest) Execute() (*ListEvents200Response, *http.Response, error) {
	return r.ApiService.ListEventsExecute(r)
}

/*
ListEvents List Events

Returns a list of Events for a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@return ApiListEventsRequest
*/
func (a *SpaceSchemaAPIService) ListEvents(
	ctx context.Context,
	spaceId string,
) ApiListEventsRequest {
	return ApiListEventsRequest{
		ApiService: a,
		ctx:        ctx,
		spaceId:    spaceId,
	}
}

// Execute executes the request
//
//	@return ListEvents200Response
func (a *SpaceSchemaAPIService) ListEventsExecute(
	r ApiListEventsRequest,
) (*ListEvents200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListEvents200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListEvents",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/events"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.pagination != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination", r.pagination, "")
	}
	if r.sortBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortBy", r.sortBy, "")
	}
	if r.sortDir != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortDir", r.sortDir, "")
	}
	if r.search != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search", r.search, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListPropertiesFromEntityRequest struct {
	ctx                 context.Context
	ApiService          *SpaceSchemaAPIService
	spaceId             string
	entitySlug          string
	pagination          *PaginationInput
	includeSampleValues *bool
	samplesCount        *float32
}

// Pagination params. Defaults to count 200.  This parameter exists in alpha.
func (r ApiListPropertiesFromEntityRequest) Pagination(
	pagination PaginationInput,
) ApiListPropertiesFromEntityRequest {
	r.pagination = &pagination
	return r
}

// When true, include sample values for each property. Defaults to false.  This parameter exists in alpha.
func (r ApiListPropertiesFromEntityRequest) IncludeSampleValues(
	includeSampleValues bool,
) ApiListPropertiesFromEntityRequest {
	r.includeSampleValues = &includeSampleValues
	return r
}

// Max number of sample values to return per property. Defaults to 20, min 1, max 100.  This parameter exists in alpha.
func (r ApiListPropertiesFromEntityRequest) SamplesCount(
	samplesCount float32,
) ApiListPropertiesFromEntityRequest {
	r.samplesCount = &samplesCount
	return r
}

func (r ApiListPropertiesFromEntityRequest) Execute() (*ListPropertiesFromEntity200Response, *http.Response, error) {
	return r.ApiService.ListPropertiesFromEntityExecute(r)
}

/*
ListPropertiesFromEntity List Properties from Entity

Returns a list of Properties for an Entity in a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

<div style="background-color: #e8f4fd; border: 1px solid #90caf9; border-radius: 6px; padding: 16px; margin: 16px 0; color: #0d47a1; line-height: 1.5;">

	<ul style="margin: 0; padding-left: 20px; font-size: 13px;">
	  <li style="margin-bottom: 6px;"><strong>Forward-only pagination</strong>: this endpoint does not support backward traversal. The <code>pagination.previous</code> field is always absent; use <code>pagination.next</code> to advance through pages.</li>
	</ul>

</div>

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@param entitySlug
	@return ApiListPropertiesFromEntityRequest
*/
func (a *SpaceSchemaAPIService) ListPropertiesFromEntity(
	ctx context.Context,
	spaceId string,
	entitySlug string,
) ApiListPropertiesFromEntityRequest {
	return ApiListPropertiesFromEntityRequest{
		ApiService: a,
		ctx:        ctx,
		spaceId:    spaceId,
		entitySlug: entitySlug,
	}
}

// Execute executes the request
//
//	@return ListPropertiesFromEntity200Response
func (a *SpaceSchemaAPIService) ListPropertiesFromEntityExecute(
	r ApiListPropertiesFromEntityRequest,
) (*ListPropertiesFromEntity200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListPropertiesFromEntity200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListPropertiesFromEntity",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/entities/{entitySlug}/properties"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"entitySlug"+"}",
		url.PathEscape(parameterValueToString(r.entitySlug, "entitySlug")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.pagination != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination", r.pagination, "")
	}
	if r.includeSampleValues != nil {
		parameterAddToHeaderOrQuery(
			localVarQueryParams,
			"includeSampleValues",
			r.includeSampleValues,
			"",
		)
	}
	if r.samplesCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "samplesCount", r.samplesCount, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListPropertiesFromEventRequest struct {
	ctx                 context.Context
	ApiService          *SpaceSchemaAPIService
	spaceId             string
	eventName           string
	pagination          *PaginationInput
	sortBy              *string
	sortDir             *string
	search              *string
	includeSampleValues *bool
	samplesCount        *float32
}

// Pagination params. Defaults to count 200.  This parameter exists in alpha.
func (r ApiListPropertiesFromEventRequest) Pagination(
	pagination PaginationInput,
) ApiListPropertiesFromEventRequest {
	r.pagination = &pagination
	return r
}

// Field to sort by. Defaults to &#39;lastSeenAt&#39;.  This parameter exists in alpha.
func (r ApiListPropertiesFromEventRequest) SortBy(sortBy string) ApiListPropertiesFromEventRequest {
	r.sortBy = &sortBy
	return r
}

// Sort direction. Defaults to &#39;desc&#39;.  This parameter exists in alpha.
func (r ApiListPropertiesFromEventRequest) SortDir(
	sortDir string,
) ApiListPropertiesFromEventRequest {
	r.sortDir = &sortDir
	return r
}

// Filter properties by name substring.  This parameter exists in alpha.
func (r ApiListPropertiesFromEventRequest) Search(search string) ApiListPropertiesFromEventRequest {
	r.search = &search
	return r
}

// When true, include sample values for each property. Defaults to false.  This parameter exists in alpha.
func (r ApiListPropertiesFromEventRequest) IncludeSampleValues(
	includeSampleValues bool,
) ApiListPropertiesFromEventRequest {
	r.includeSampleValues = &includeSampleValues
	return r
}

// Max number of sample values to return per property. Defaults to 20, min 1, max 100.  This parameter exists in alpha.
func (r ApiListPropertiesFromEventRequest) SamplesCount(
	samplesCount float32,
) ApiListPropertiesFromEventRequest {
	r.samplesCount = &samplesCount
	return r
}

func (r ApiListPropertiesFromEventRequest) Execute() (*ListPropertiesFromEvent200Response, *http.Response, error) {
	return r.ApiService.ListPropertiesFromEventExecute(r)
}

/*
ListPropertiesFromEvent List Properties from Event

Returns a list of Properties for an Event in a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@param eventName
	@return ApiListPropertiesFromEventRequest
*/
func (a *SpaceSchemaAPIService) ListPropertiesFromEvent(
	ctx context.Context,
	spaceId string,
	eventName string,
) ApiListPropertiesFromEventRequest {
	return ApiListPropertiesFromEventRequest{
		ApiService: a,
		ctx:        ctx,
		spaceId:    spaceId,
		eventName:  eventName,
	}
}

// Execute executes the request
//
//	@return ListPropertiesFromEvent200Response
func (a *SpaceSchemaAPIService) ListPropertiesFromEventExecute(
	r ApiListPropertiesFromEventRequest,
) (*ListPropertiesFromEvent200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListPropertiesFromEvent200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListPropertiesFromEvent",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/events/{eventName}/properties"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"eventName"+"}",
		url.PathEscape(parameterValueToString(r.eventName, "eventName")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.pagination != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination", r.pagination, "")
	}
	if r.sortBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortBy", r.sortBy, "")
	}
	if r.sortDir != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortDir", r.sortDir, "")
	}
	if r.search != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search", r.search, "")
	}
	if r.includeSampleValues != nil {
		parameterAddToHeaderOrQuery(
			localVarQueryParams,
			"includeSampleValues",
			r.includeSampleValues,
			"",
		)
	}
	if r.samplesCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "samplesCount", r.samplesCount, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListSampleValuesFromEntityPropertyRequest struct {
	ctx          context.Context
	ApiService   *SpaceSchemaAPIService
	spaceId      string
	entitySlug   string
	propertyName string
}

func (r ApiListSampleValuesFromEntityPropertyRequest) Execute() (*ListSampleValuesFromEntityProperty200Response, *http.Response, error) {
	return r.ApiService.ListSampleValuesFromEntityPropertyExecute(r)
}

/*
ListSampleValuesFromEntityProperty List Sample Values from Entity Property

Returns sample values for an Entity Property in a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@param entitySlug
	@param propertyName
	@return ApiListSampleValuesFromEntityPropertyRequest
*/
func (a *SpaceSchemaAPIService) ListSampleValuesFromEntityProperty(
	ctx context.Context,
	spaceId string,
	entitySlug string,
	propertyName string,
) ApiListSampleValuesFromEntityPropertyRequest {
	return ApiListSampleValuesFromEntityPropertyRequest{
		ApiService:   a,
		ctx:          ctx,
		spaceId:      spaceId,
		entitySlug:   entitySlug,
		propertyName: propertyName,
	}
}

// Execute executes the request
//
//	@return ListSampleValuesFromEntityProperty200Response
func (a *SpaceSchemaAPIService) ListSampleValuesFromEntityPropertyExecute(
	r ApiListSampleValuesFromEntityPropertyRequest,
) (*ListSampleValuesFromEntityProperty200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListSampleValuesFromEntityProperty200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListSampleValuesFromEntityProperty",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/entities/{entitySlug}/properties/{propertyName}/sample-values"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"entitySlug"+"}",
		url.PathEscape(parameterValueToString(r.entitySlug, "entitySlug")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"propertyName"+"}",
		url.PathEscape(parameterValueToString(r.propertyName, "propertyName")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListSampleValuesFromEventPropertyRequest struct {
	ctx          context.Context
	ApiService   *SpaceSchemaAPIService
	spaceId      string
	eventName    string
	propertyName string
	propertyType *EventPropertyType
}

// The property type.  This parameter exists in alpha.
func (r ApiListSampleValuesFromEventPropertyRequest) PropertyType(
	propertyType EventPropertyType,
) ApiListSampleValuesFromEventPropertyRequest {
	r.propertyType = &propertyType
	return r
}

func (r ApiListSampleValuesFromEventPropertyRequest) Execute() (*ListSampleValuesFromEventProperty200Response, *http.Response, error) {
	return r.ApiService.ListSampleValuesFromEventPropertyExecute(r)
}

/*
ListSampleValuesFromEventProperty List Sample Values from Event Property

Returns sample values for an Event Property in a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@param eventName
	@param propertyName
	@return ApiListSampleValuesFromEventPropertyRequest
*/
func (a *SpaceSchemaAPIService) ListSampleValuesFromEventProperty(
	ctx context.Context,
	spaceId string,
	eventName string,
	propertyName string,
) ApiListSampleValuesFromEventPropertyRequest {
	return ApiListSampleValuesFromEventPropertyRequest{
		ApiService:   a,
		ctx:          ctx,
		spaceId:      spaceId,
		eventName:    eventName,
		propertyName: propertyName,
	}
}

// Execute executes the request
//
//	@return ListSampleValuesFromEventProperty200Response
func (a *SpaceSchemaAPIService) ListSampleValuesFromEventPropertyExecute(
	r ApiListSampleValuesFromEventPropertyRequest,
) (*ListSampleValuesFromEventProperty200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListSampleValuesFromEventProperty200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListSampleValuesFromEventProperty",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/events/{eventName}/properties/{propertyName}/sample-values"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"eventName"+"}",
		url.PathEscape(parameterValueToString(r.eventName, "eventName")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"propertyName"+"}",
		url.PathEscape(parameterValueToString(r.propertyName, "propertyName")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.propertyType == nil {
		return localVarReturnValue, nil, reportError(
			"propertyType is required and must be specified",
		)
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "propertyType", r.propertyType, "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListSampleValuesFromTraitRequest struct {
	ctx        context.Context
	ApiService *SpaceSchemaAPIService
	spaceId    string
	traitKey   string
	collection *string
}

// Collection to get trait values for. Defaults to &#39;users&#39;.  This parameter exists in alpha.
func (r ApiListSampleValuesFromTraitRequest) Collection(
	collection string,
) ApiListSampleValuesFromTraitRequest {
	r.collection = &collection
	return r
}

func (r ApiListSampleValuesFromTraitRequest) Execute() (*ListSampleValuesFromTrait200Response, *http.Response, error) {
	return r.ApiService.ListSampleValuesFromTraitExecute(r)
}

/*
ListSampleValuesFromTrait List Sample Values from Trait

Returns sample values for a Trait in a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@param traitKey
	@return ApiListSampleValuesFromTraitRequest
*/
func (a *SpaceSchemaAPIService) ListSampleValuesFromTrait(
	ctx context.Context,
	spaceId string,
	traitKey string,
) ApiListSampleValuesFromTraitRequest {
	return ApiListSampleValuesFromTraitRequest{
		ApiService: a,
		ctx:        ctx,
		spaceId:    spaceId,
		traitKey:   traitKey,
	}
}

// Execute executes the request
//
//	@return ListSampleValuesFromTrait200Response
func (a *SpaceSchemaAPIService) ListSampleValuesFromTraitExecute(
	r ApiListSampleValuesFromTraitRequest,
) (*ListSampleValuesFromTrait200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListSampleValuesFromTrait200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListSampleValuesFromTrait",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/traits/{traitKey}/sample-values"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"traitKey"+"}",
		url.PathEscape(parameterValueToString(r.traitKey, "traitKey")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.collection != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "collection", r.collection, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListTraitsRequest struct {
	ctx                 context.Context
	ApiService          *SpaceSchemaAPIService
	spaceId             string
	pagination          *PaginationInput
	sortBy              *string
	sortDir             *string
	search              *string
	collection          *string
	includeSampleValues *bool
	samplesCount        *float32
}

// Pagination params. Defaults to count 200.  This parameter exists in alpha.
func (r ApiListTraitsRequest) Pagination(pagination PaginationInput) ApiListTraitsRequest {
	r.pagination = &pagination
	return r
}

// Field to sort by. Defaults to &#39;trait&#39;.  This parameter exists in alpha.
func (r ApiListTraitsRequest) SortBy(sortBy string) ApiListTraitsRequest {
	r.sortBy = &sortBy
	return r
}

// Sort direction. Defaults to &#39;asc&#39;.  This parameter exists in alpha.
func (r ApiListTraitsRequest) SortDir(sortDir string) ApiListTraitsRequest {
	r.sortDir = &sortDir
	return r
}

// Filter traits by key substring.  This parameter exists in alpha.
func (r ApiListTraitsRequest) Search(search string) ApiListTraitsRequest {
	r.search = &search
	return r
}

// Collection to list traits for. Defaults to &#39;users&#39;.  This parameter exists in alpha.
func (r ApiListTraitsRequest) Collection(collection string) ApiListTraitsRequest {
	r.collection = &collection
	return r
}

// When true, include sample values for each trait. Defaults to false.  This parameter exists in alpha.
func (r ApiListTraitsRequest) IncludeSampleValues(includeSampleValues bool) ApiListTraitsRequest {
	r.includeSampleValues = &includeSampleValues
	return r
}

// Max number of sample values to return per trait. Defaults to 20, min 1, max 100.  This parameter exists in alpha.
func (r ApiListTraitsRequest) SamplesCount(samplesCount float32) ApiListTraitsRequest {
	r.samplesCount = &samplesCount
	return r
}

func (r ApiListTraitsRequest) Execute() (*ListTraits200Response, *http.Response, error) {
	return r.ApiService.ListTraitsExecute(r)
}

/*
ListTraits List Traits

Returns a list of Traits for a Space.

• This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com.

<div style="background-color: #e8f4fd; border: 1px solid #90caf9; border-radius: 6px; padding: 16px; margin: 16px 0; color: #0d47a1; line-height: 1.5;">

	<ul style="margin: 0; padding-left: 20px; font-size: 13px;">
	  <li style="margin-bottom: 6px;"><strong>Forward-only pagination</strong>: this endpoint does not support backward traversal. The <code>pagination.previous</code> field is always absent; use <code>pagination.next</code> to advance through pages.</li>
	  <li style="margin-bottom: 6px;"><strong>Approximate total count</strong>: <code>pagination.totalEntries</code> is an upper bound that decreases as you paginate — the final page reflects the exact deduplicated count.</li>
	  <li style="margin-bottom: 6px;"><strong>Duplicate entries</strong>: when sorting by <code>lastSeenAt</code>, duplicate trait entries may appear across pages for Spaces with more than 2,500 traits. Sorting by <code>trait</code> is not affected.</li>
	</ul>

</div>

The rate limit for this endpoint is 25 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param spaceId
	@return ApiListTraitsRequest
*/
func (a *SpaceSchemaAPIService) ListTraits(
	ctx context.Context,
	spaceId string,
) ApiListTraitsRequest {
	return ApiListTraitsRequest{
		ApiService: a,
		ctx:        ctx,
		spaceId:    spaceId,
	}
}

// Execute executes the request
//
//	@return ListTraits200Response
func (a *SpaceSchemaAPIService) ListTraitsExecute(
	r ApiListTraitsRequest,
) (*ListTraits200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListTraits200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(
		r.ctx,
		"SpaceSchemaAPIService.ListTraits",
	)
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/spaces/{spaceId}/traits"
	localVarPath = strings.Replace(
		localVarPath,
		"{"+"spaceId"+"}",
		url.PathEscape(parameterValueToString(r.spaceId, "spaceId")),
		-1,
	)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.pagination != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination", r.pagination, "")
	}
	if r.sortBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortBy", r.sortBy, "")
	}
	if r.sortDir != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sortDir", r.sortDir, "")
	}
	if r.search != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "search", r.search, "")
	}
	if r.collection != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "collection", r.collection, "")
	}
	if r.includeSampleValues != nil {
		parameterAddToHeaderOrQuery(
			localVarQueryParams,
			"includeSampleValues",
			r.includeSampleValues,
			"",
		)
	}
	if r.samplesCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "samplesCount", r.samplesCount, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{
		"application/vnd.segment.v1alpha+json",
		"application/json",
	}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(
		r.ctx,
		localVarPath,
		localVarHTTPMethod,
		localVarPostBody,
		localVarHeaderParams,
		localVarQueryParams,
		localVarFormParams,
		formFiles,
	)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v RequestErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(
		&localVarReturnValue,
		localVarBody,
		localVarHTTPResponse.Header.Get("Content-Type"),
	)
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
