/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 50.1.0
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AudienceCreateOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceCreateOptions{}

// AudienceCreateOptions struct for AudienceCreateOptions
type AudienceCreateOptions struct {
	IncludeHistorical *bool `json:"includeHistorical,omitempty"`
	IncludeAnonymous  *bool `json:"includeAnonymous,omitempty"`
}

// NewAudienceCreateOptions instantiates a new AudienceCreateOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudienceCreateOptions() *AudienceCreateOptions {
	this := AudienceCreateOptions{}
	return &this
}

// NewAudienceCreateOptionsWithDefaults instantiates a new AudienceCreateOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceCreateOptionsWithDefaults() *AudienceCreateOptions {
	this := AudienceCreateOptions{}
	return &this
}

// GetIncludeHistorical returns the IncludeHistorical field value if set, zero value otherwise.
func (o *AudienceCreateOptions) GetIncludeHistorical() bool {
	if o == nil || IsNil(o.IncludeHistorical) {
		var ret bool
		return ret
	}
	return *o.IncludeHistorical
}

// GetIncludeHistoricalOk returns a tuple with the IncludeHistorical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceCreateOptions) GetIncludeHistoricalOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeHistorical) {
		return nil, false
	}
	return o.IncludeHistorical, true
}

// HasIncludeHistorical returns a boolean if a field has been set.
func (o *AudienceCreateOptions) HasIncludeHistorical() bool {
	if o != nil && !IsNil(o.IncludeHistorical) {
		return true
	}

	return false
}

// SetIncludeHistorical gets a reference to the given bool and assigns it to the IncludeHistorical field.
func (o *AudienceCreateOptions) SetIncludeHistorical(v bool) {
	o.IncludeHistorical = &v
}

// GetIncludeAnonymous returns the IncludeAnonymous field value if set, zero value otherwise.
func (o *AudienceCreateOptions) GetIncludeAnonymous() bool {
	if o == nil || IsNil(o.IncludeAnonymous) {
		var ret bool
		return ret
	}
	return *o.IncludeAnonymous
}

// GetIncludeAnonymousOk returns a tuple with the IncludeAnonymous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceCreateOptions) GetIncludeAnonymousOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeAnonymous) {
		return nil, false
	}
	return o.IncludeAnonymous, true
}

// HasIncludeAnonymous returns a boolean if a field has been set.
func (o *AudienceCreateOptions) HasIncludeAnonymous() bool {
	if o != nil && !IsNil(o.IncludeAnonymous) {
		return true
	}

	return false
}

// SetIncludeAnonymous gets a reference to the given bool and assigns it to the IncludeAnonymous field.
func (o *AudienceCreateOptions) SetIncludeAnonymous(v bool) {
	o.IncludeAnonymous = &v
}

func (o AudienceCreateOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceCreateOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeHistorical) {
		toSerialize["includeHistorical"] = o.IncludeHistorical
	}
	if !IsNil(o.IncludeAnonymous) {
		toSerialize["includeAnonymous"] = o.IncludeAnonymous
	}
	return toSerialize, nil
}

type NullableAudienceCreateOptions struct {
	value *AudienceCreateOptions
	isSet bool
}

func (v NullableAudienceCreateOptions) Get() *AudienceCreateOptions {
	return v.value
}

func (v *NullableAudienceCreateOptions) Set(val *AudienceCreateOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceCreateOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceCreateOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudienceCreateOptions(val *AudienceCreateOptions) *NullableAudienceCreateOptions {
	return &NullableAudienceCreateOptions{value: val, isSet: true}
}

func (v NullableAudienceCreateOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceCreateOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
