/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 72.1.0
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateDestinationForAudienceAlphaOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDestinationForAudienceAlphaOutput{}

// UpdateDestinationForAudienceAlphaOutput Output for updating a Destination for an Audience.
type UpdateDestinationForAudienceAlphaOutput struct {
	Destination Destination `json:"destination"`
	// The id sync configuration for the Destination - array of external ids with their strategies.
	IdSyncConfiguration []IDSyncConfigurationInput `json:"idSyncConfiguration,omitempty"`
	// The settings that a Destination requires to create audiences on a third-party platform.
	ConnectionSettings interface{} `json:"connectionSettings,omitempty"`
}

// NewUpdateDestinationForAudienceAlphaOutput instantiates a new UpdateDestinationForAudienceAlphaOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDestinationForAudienceAlphaOutput(
	destination Destination,
) *UpdateDestinationForAudienceAlphaOutput {
	this := UpdateDestinationForAudienceAlphaOutput{}
	this.Destination = destination
	return &this
}

// NewUpdateDestinationForAudienceAlphaOutputWithDefaults instantiates a new UpdateDestinationForAudienceAlphaOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDestinationForAudienceAlphaOutputWithDefaults() *UpdateDestinationForAudienceAlphaOutput {
	this := UpdateDestinationForAudienceAlphaOutput{}
	return &this
}

// GetDestination returns the Destination field value
func (o *UpdateDestinationForAudienceAlphaOutput) GetDestination() Destination {
	if o == nil {
		var ret Destination
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *UpdateDestinationForAudienceAlphaOutput) GetDestinationOk() (*Destination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *UpdateDestinationForAudienceAlphaOutput) SetDestination(v Destination) {
	o.Destination = v
}

// GetIdSyncConfiguration returns the IdSyncConfiguration field value if set, zero value otherwise.
func (o *UpdateDestinationForAudienceAlphaOutput) GetIdSyncConfiguration() []IDSyncConfigurationInput {
	if o == nil || IsNil(o.IdSyncConfiguration) {
		var ret []IDSyncConfigurationInput
		return ret
	}
	return o.IdSyncConfiguration
}

// GetIdSyncConfigurationOk returns a tuple with the IdSyncConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDestinationForAudienceAlphaOutput) GetIdSyncConfigurationOk() ([]IDSyncConfigurationInput, bool) {
	if o == nil || IsNil(o.IdSyncConfiguration) {
		return nil, false
	}
	return o.IdSyncConfiguration, true
}

// HasIdSyncConfiguration returns a boolean if a field has been set.
func (o *UpdateDestinationForAudienceAlphaOutput) HasIdSyncConfiguration() bool {
	if o != nil && !IsNil(o.IdSyncConfiguration) {
		return true
	}

	return false
}

// SetIdSyncConfiguration gets a reference to the given []IDSyncConfigurationInput and assigns it to the IdSyncConfiguration field.
func (o *UpdateDestinationForAudienceAlphaOutput) SetIdSyncConfiguration(
	v []IDSyncConfigurationInput,
) {
	o.IdSyncConfiguration = v
}

// GetConnectionSettings returns the ConnectionSettings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateDestinationForAudienceAlphaOutput) GetConnectionSettings() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ConnectionSettings
}

// GetConnectionSettingsOk returns a tuple with the ConnectionSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateDestinationForAudienceAlphaOutput) GetConnectionSettingsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ConnectionSettings) {
		return nil, false
	}
	return &o.ConnectionSettings, true
}

// HasConnectionSettings returns a boolean if a field has been set.
func (o *UpdateDestinationForAudienceAlphaOutput) HasConnectionSettings() bool {
	if o != nil && IsNil(o.ConnectionSettings) {
		return true
	}

	return false
}

// SetConnectionSettings gets a reference to the given interface{} and assigns it to the ConnectionSettings field.
func (o *UpdateDestinationForAudienceAlphaOutput) SetConnectionSettings(v interface{}) {
	o.ConnectionSettings = v
}

func (o UpdateDestinationForAudienceAlphaOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDestinationForAudienceAlphaOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destination"] = o.Destination
	if !IsNil(o.IdSyncConfiguration) {
		toSerialize["idSyncConfiguration"] = o.IdSyncConfiguration
	}
	if o.ConnectionSettings != nil {
		toSerialize["connectionSettings"] = o.ConnectionSettings
	}
	return toSerialize, nil
}

type NullableUpdateDestinationForAudienceAlphaOutput struct {
	value *UpdateDestinationForAudienceAlphaOutput
	isSet bool
}

func (v NullableUpdateDestinationForAudienceAlphaOutput) Get() *UpdateDestinationForAudienceAlphaOutput {
	return v.value
}

func (v *NullableUpdateDestinationForAudienceAlphaOutput) Set(
	val *UpdateDestinationForAudienceAlphaOutput,
) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDestinationForAudienceAlphaOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDestinationForAudienceAlphaOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDestinationForAudienceAlphaOutput(
	val *UpdateDestinationForAudienceAlphaOutput,
) *NullableUpdateDestinationForAudienceAlphaOutput {
	return &NullableUpdateDestinationForAudienceAlphaOutput{value: val, isSet: true}
}

func (v NullableUpdateDestinationForAudienceAlphaOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDestinationForAudienceAlphaOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
