/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 61.1.3
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the GetAudiencePreviewAlphaOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAudiencePreviewAlphaOutput{}

// GetAudiencePreviewAlphaOutput Output when reading an audience preview.
type GetAudiencePreviewAlphaOutput struct {
	AudiencePreview AudiencePreview `json:"audiencePreview"`
}

// NewGetAudiencePreviewAlphaOutput instantiates a new GetAudiencePreviewAlphaOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAudiencePreviewAlphaOutput(
	audiencePreview AudiencePreview,
) *GetAudiencePreviewAlphaOutput {
	this := GetAudiencePreviewAlphaOutput{}
	this.AudiencePreview = audiencePreview
	return &this
}

// NewGetAudiencePreviewAlphaOutputWithDefaults instantiates a new GetAudiencePreviewAlphaOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAudiencePreviewAlphaOutputWithDefaults() *GetAudiencePreviewAlphaOutput {
	this := GetAudiencePreviewAlphaOutput{}
	return &this
}

// GetAudiencePreview returns the AudiencePreview field value
func (o *GetAudiencePreviewAlphaOutput) GetAudiencePreview() AudiencePreview {
	if o == nil {
		var ret AudiencePreview
		return ret
	}

	return o.AudiencePreview
}

// GetAudiencePreviewOk returns a tuple with the AudiencePreview field value
// and a boolean to check if the value has been set.
func (o *GetAudiencePreviewAlphaOutput) GetAudiencePreviewOk() (*AudiencePreview, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudiencePreview, true
}

// SetAudiencePreview sets field value
func (o *GetAudiencePreviewAlphaOutput) SetAudiencePreview(v AudiencePreview) {
	o.AudiencePreview = v
}

func (o GetAudiencePreviewAlphaOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAudiencePreviewAlphaOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audiencePreview"] = o.AudiencePreview
	return toSerialize, nil
}

type NullableGetAudiencePreviewAlphaOutput struct {
	value *GetAudiencePreviewAlphaOutput
	isSet bool
}

func (v NullableGetAudiencePreviewAlphaOutput) Get() *GetAudiencePreviewAlphaOutput {
	return v.value
}

func (v *NullableGetAudiencePreviewAlphaOutput) Set(val *GetAudiencePreviewAlphaOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAudiencePreviewAlphaOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAudiencePreviewAlphaOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAudiencePreviewAlphaOutput(
	val *GetAudiencePreviewAlphaOutput,
) *NullableGetAudiencePreviewAlphaOutput {
	return &NullableGetAudiencePreviewAlphaOutput{value: val, isSet: true}
}

func (v NullableGetAudiencePreviewAlphaOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAudiencePreviewAlphaOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
