/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 73.2.0
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ListCredentialConsumersV1Output type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCredentialConsumersV1Output{}

// ListCredentialConsumersV1Output Returns the Warehouses and Sources that consume a Credential. The two lists are paginated independently, so a caller can page through one without affecting the other.
type ListCredentialConsumersV1Output struct {
	// The Warehouses that use this Credential.
	Warehouses           []WarehouseV1    `json:"warehouses"`
	WarehousesPagination PaginationOutput `json:"warehousesPagination"`
	// The Sources that use this Credential.
	Sources           []SourceV1       `json:"sources"`
	SourcesPagination PaginationOutput `json:"sourcesPagination"`
}

// NewListCredentialConsumersV1Output instantiates a new ListCredentialConsumersV1Output object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCredentialConsumersV1Output(
	warehouses []WarehouseV1,
	warehousesPagination PaginationOutput,
	sources []SourceV1,
	sourcesPagination PaginationOutput,
) *ListCredentialConsumersV1Output {
	this := ListCredentialConsumersV1Output{}
	this.Warehouses = warehouses
	this.WarehousesPagination = warehousesPagination
	this.Sources = sources
	this.SourcesPagination = sourcesPagination
	return &this
}

// NewListCredentialConsumersV1OutputWithDefaults instantiates a new ListCredentialConsumersV1Output object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCredentialConsumersV1OutputWithDefaults() *ListCredentialConsumersV1Output {
	this := ListCredentialConsumersV1Output{}
	return &this
}

// GetWarehouses returns the Warehouses field value
func (o *ListCredentialConsumersV1Output) GetWarehouses() []WarehouseV1 {
	if o == nil {
		var ret []WarehouseV1
		return ret
	}

	return o.Warehouses
}

// GetWarehousesOk returns a tuple with the Warehouses field value
// and a boolean to check if the value has been set.
func (o *ListCredentialConsumersV1Output) GetWarehousesOk() ([]WarehouseV1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Warehouses, true
}

// SetWarehouses sets field value
func (o *ListCredentialConsumersV1Output) SetWarehouses(v []WarehouseV1) {
	o.Warehouses = v
}

// GetWarehousesPagination returns the WarehousesPagination field value
func (o *ListCredentialConsumersV1Output) GetWarehousesPagination() PaginationOutput {
	if o == nil {
		var ret PaginationOutput
		return ret
	}

	return o.WarehousesPagination
}

// GetWarehousesPaginationOk returns a tuple with the WarehousesPagination field value
// and a boolean to check if the value has been set.
func (o *ListCredentialConsumersV1Output) GetWarehousesPaginationOk() (*PaginationOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarehousesPagination, true
}

// SetWarehousesPagination sets field value
func (o *ListCredentialConsumersV1Output) SetWarehousesPagination(v PaginationOutput) {
	o.WarehousesPagination = v
}

// GetSources returns the Sources field value
func (o *ListCredentialConsumersV1Output) GetSources() []SourceV1 {
	if o == nil {
		var ret []SourceV1
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *ListCredentialConsumersV1Output) GetSourcesOk() ([]SourceV1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sources, true
}

// SetSources sets field value
func (o *ListCredentialConsumersV1Output) SetSources(v []SourceV1) {
	o.Sources = v
}

// GetSourcesPagination returns the SourcesPagination field value
func (o *ListCredentialConsumersV1Output) GetSourcesPagination() PaginationOutput {
	if o == nil {
		var ret PaginationOutput
		return ret
	}

	return o.SourcesPagination
}

// GetSourcesPaginationOk returns a tuple with the SourcesPagination field value
// and a boolean to check if the value has been set.
func (o *ListCredentialConsumersV1Output) GetSourcesPaginationOk() (*PaginationOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourcesPagination, true
}

// SetSourcesPagination sets field value
func (o *ListCredentialConsumersV1Output) SetSourcesPagination(v PaginationOutput) {
	o.SourcesPagination = v
}

func (o ListCredentialConsumersV1Output) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCredentialConsumersV1Output) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["warehouses"] = o.Warehouses
	toSerialize["warehousesPagination"] = o.WarehousesPagination
	toSerialize["sources"] = o.Sources
	toSerialize["sourcesPagination"] = o.SourcesPagination
	return toSerialize, nil
}

type NullableListCredentialConsumersV1Output struct {
	value *ListCredentialConsumersV1Output
	isSet bool
}

func (v NullableListCredentialConsumersV1Output) Get() *ListCredentialConsumersV1Output {
	return v.value
}

func (v *NullableListCredentialConsumersV1Output) Set(val *ListCredentialConsumersV1Output) {
	v.value = val
	v.isSet = true
}

func (v NullableListCredentialConsumersV1Output) IsSet() bool {
	return v.isSet
}

func (v *NullableListCredentialConsumersV1Output) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCredentialConsumersV1Output(
	val *ListCredentialConsumersV1Output,
) *NullableListCredentialConsumersV1Output {
	return &NullableListCredentialConsumersV1Output{value: val, isSet: true}
}

func (v NullableListCredentialConsumersV1Output) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCredentialConsumersV1Output) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
