/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 58.1.1
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ExitRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExitRule{}

// ExitRule struct for ExitRule
type ExitRule struct {
	Type                  string   `json:"type"`
	ExitType              string   `json:"exitType"`
	Enabled               bool     `json:"enabled"`
	ConcurrencyEnabled    bool     `json:"concurrencyEnabled"`
	ConnectedDestinations []string `json:"connectedDestinations,omitempty"`
	Key                   Key      `json:"key"`
}

// NewExitRule instantiates a new ExitRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExitRule(
	type_ string,
	exitType string,
	enabled bool,
	concurrencyEnabled bool,
	key Key,
) *ExitRule {
	this := ExitRule{}
	this.Type = type_
	this.ExitType = exitType
	this.Enabled = enabled
	this.ConcurrencyEnabled = concurrencyEnabled
	this.Key = key
	return &this
}

// NewExitRuleWithDefaults instantiates a new ExitRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExitRuleWithDefaults() *ExitRule {
	this := ExitRule{}
	return &this
}

// GetType returns the Type field value
func (o *ExitRule) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ExitRule) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ExitRule) SetType(v string) {
	o.Type = v
}

// GetExitType returns the ExitType field value
func (o *ExitRule) GetExitType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExitType
}

// GetExitTypeOk returns a tuple with the ExitType field value
// and a boolean to check if the value has been set.
func (o *ExitRule) GetExitTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExitType, true
}

// SetExitType sets field value
func (o *ExitRule) SetExitType(v string) {
	o.ExitType = v
}

// GetEnabled returns the Enabled field value
func (o *ExitRule) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ExitRule) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ExitRule) SetEnabled(v bool) {
	o.Enabled = v
}

// GetConcurrencyEnabled returns the ConcurrencyEnabled field value
func (o *ExitRule) GetConcurrencyEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ConcurrencyEnabled
}

// GetConcurrencyEnabledOk returns a tuple with the ConcurrencyEnabled field value
// and a boolean to check if the value has been set.
func (o *ExitRule) GetConcurrencyEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConcurrencyEnabled, true
}

// SetConcurrencyEnabled sets field value
func (o *ExitRule) SetConcurrencyEnabled(v bool) {
	o.ConcurrencyEnabled = v
}

// GetConnectedDestinations returns the ConnectedDestinations field value if set, zero value otherwise.
func (o *ExitRule) GetConnectedDestinations() []string {
	if o == nil || IsNil(o.ConnectedDestinations) {
		var ret []string
		return ret
	}
	return o.ConnectedDestinations
}

// GetConnectedDestinationsOk returns a tuple with the ConnectedDestinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExitRule) GetConnectedDestinationsOk() ([]string, bool) {
	if o == nil || IsNil(o.ConnectedDestinations) {
		return nil, false
	}
	return o.ConnectedDestinations, true
}

// HasConnectedDestinations returns a boolean if a field has been set.
func (o *ExitRule) HasConnectedDestinations() bool {
	if o != nil && !IsNil(o.ConnectedDestinations) {
		return true
	}

	return false
}

// SetConnectedDestinations gets a reference to the given []string and assigns it to the ConnectedDestinations field.
func (o *ExitRule) SetConnectedDestinations(v []string) {
	o.ConnectedDestinations = v
}

// GetKey returns the Key field value
func (o *ExitRule) GetKey() Key {
	if o == nil {
		var ret Key
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ExitRule) GetKeyOk() (*Key, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ExitRule) SetKey(v Key) {
	o.Key = v
}

func (o ExitRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExitRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["exitType"] = o.ExitType
	toSerialize["enabled"] = o.Enabled
	toSerialize["concurrencyEnabled"] = o.ConcurrencyEnabled
	if !IsNil(o.ConnectedDestinations) {
		toSerialize["connectedDestinations"] = o.ConnectedDestinations
	}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

type NullableExitRule struct {
	value *ExitRule
	isSet bool
}

func (v NullableExitRule) Get() *ExitRule {
	return v.value
}

func (v *NullableExitRule) Set(val *ExitRule) {
	v.value = val
	v.isSet = true
}

func (v NullableExitRule) IsSet() bool {
	return v.isSet
}

func (v *NullableExitRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExitRule(val *ExitRule) *NullableExitRule {
	return &NullableExitRule{value: val, isSet: true}
}

func (v NullableExitRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExitRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
