/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 46.0.0
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the RestoreFunctionVersion200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestoreFunctionVersion200Response{}

// RestoreFunctionVersion200Response struct for RestoreFunctionVersion200Response
type RestoreFunctionVersion200Response struct {
	Data *RestoreFunctionVersionAlphaOutput `json:"data,omitempty"`
}

// NewRestoreFunctionVersion200Response instantiates a new RestoreFunctionVersion200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreFunctionVersion200Response() *RestoreFunctionVersion200Response {
	this := RestoreFunctionVersion200Response{}
	return &this
}

// NewRestoreFunctionVersion200ResponseWithDefaults instantiates a new RestoreFunctionVersion200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreFunctionVersion200ResponseWithDefaults() *RestoreFunctionVersion200Response {
	this := RestoreFunctionVersion200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RestoreFunctionVersion200Response) GetData() RestoreFunctionVersionAlphaOutput {
	if o == nil || IsNil(o.Data) {
		var ret RestoreFunctionVersionAlphaOutput
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreFunctionVersion200Response) GetDataOk() (*RestoreFunctionVersionAlphaOutput, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RestoreFunctionVersion200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RestoreFunctionVersionAlphaOutput and assigns it to the Data field.
func (o *RestoreFunctionVersion200Response) SetData(v RestoreFunctionVersionAlphaOutput) {
	o.Data = &v
}

func (o RestoreFunctionVersion200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestoreFunctionVersion200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableRestoreFunctionVersion200Response struct {
	value *RestoreFunctionVersion200Response
	isSet bool
}

func (v NullableRestoreFunctionVersion200Response) Get() *RestoreFunctionVersion200Response {
	return v.value
}

func (v *NullableRestoreFunctionVersion200Response) Set(val *RestoreFunctionVersion200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreFunctionVersion200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreFunctionVersion200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreFunctionVersion200Response(
	val *RestoreFunctionVersion200Response,
) *NullableRestoreFunctionVersion200Response {
	return &NullableRestoreFunctionVersion200Response{value: val, isSet: true}
}

func (v NullableRestoreFunctionVersion200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreFunctionVersion200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
