/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 69.0.0
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateAudienceForSpaceOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAudienceForSpaceOutput{}

// UpdateAudienceForSpaceOutput Audience output for update.
type UpdateAudienceForSpaceOutput struct {
	Audience AudienceSummary `json:"audience"`
}

// NewUpdateAudienceForSpaceOutput instantiates a new UpdateAudienceForSpaceOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAudienceForSpaceOutput(audience AudienceSummary) *UpdateAudienceForSpaceOutput {
	this := UpdateAudienceForSpaceOutput{}
	this.Audience = audience
	return &this
}

// NewUpdateAudienceForSpaceOutputWithDefaults instantiates a new UpdateAudienceForSpaceOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAudienceForSpaceOutputWithDefaults() *UpdateAudienceForSpaceOutput {
	this := UpdateAudienceForSpaceOutput{}
	return &this
}

// GetAudience returns the Audience field value
func (o *UpdateAudienceForSpaceOutput) GetAudience() AudienceSummary {
	if o == nil {
		var ret AudienceSummary
		return ret
	}

	return o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value
// and a boolean to check if the value has been set.
func (o *UpdateAudienceForSpaceOutput) GetAudienceOk() (*AudienceSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audience, true
}

// SetAudience sets field value
func (o *UpdateAudienceForSpaceOutput) SetAudience(v AudienceSummary) {
	o.Audience = v
}

func (o UpdateAudienceForSpaceOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAudienceForSpaceOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audience"] = o.Audience
	return toSerialize, nil
}

type NullableUpdateAudienceForSpaceOutput struct {
	value *UpdateAudienceForSpaceOutput
	isSet bool
}

func (v NullableUpdateAudienceForSpaceOutput) Get() *UpdateAudienceForSpaceOutput {
	return v.value
}

func (v *NullableUpdateAudienceForSpaceOutput) Set(val *UpdateAudienceForSpaceOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAudienceForSpaceOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAudienceForSpaceOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAudienceForSpaceOutput(
	val *UpdateAudienceForSpaceOutput,
) *NullableUpdateAudienceForSpaceOutput {
	return &NullableUpdateAudienceForSpaceOutput{value: val, isSet: true}
}

func (v NullableUpdateAudienceForSpaceOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAudienceForSpaceOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
