/*
Segment Public API

The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.

API version: 62.0.4
Contact: friends@segment.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ListSupportedDestinationsFromAudienceAlphaOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSupportedDestinationsFromAudienceAlphaOutput{}

// ListSupportedDestinationsFromAudienceAlphaOutput struct for ListSupportedDestinationsFromAudienceAlphaOutput
type ListSupportedDestinationsFromAudienceAlphaOutput struct {
	// The Destinations available for activation.
	Destinations map[string]interface{} `json:"destinations"`
	Pagination   *PaginationOutput      `json:"pagination,omitempty"`
}

// NewListSupportedDestinationsFromAudienceAlphaOutput instantiates a new ListSupportedDestinationsFromAudienceAlphaOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSupportedDestinationsFromAudienceAlphaOutput(
	destinations map[string]interface{},
) *ListSupportedDestinationsFromAudienceAlphaOutput {
	this := ListSupportedDestinationsFromAudienceAlphaOutput{}
	this.Destinations = destinations
	return &this
}

// NewListSupportedDestinationsFromAudienceAlphaOutputWithDefaults instantiates a new ListSupportedDestinationsFromAudienceAlphaOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSupportedDestinationsFromAudienceAlphaOutputWithDefaults() *ListSupportedDestinationsFromAudienceAlphaOutput {
	this := ListSupportedDestinationsFromAudienceAlphaOutput{}
	return &this
}

// GetDestinations returns the Destinations field value
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) GetDestinations() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value
// and a boolean to check if the value has been set.
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) GetDestinationsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Destinations, true
}

// SetDestinations sets field value
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) SetDestinations(
	v map[string]interface{},
) {
	o.Destinations = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) GetPagination() PaginationOutput {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationOutput
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) GetPaginationOk() (*PaginationOutput, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationOutput and assigns it to the Pagination field.
func (o *ListSupportedDestinationsFromAudienceAlphaOutput) SetPagination(v PaginationOutput) {
	o.Pagination = &v
}

func (o ListSupportedDestinationsFromAudienceAlphaOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSupportedDestinationsFromAudienceAlphaOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destinations"] = o.Destinations
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListSupportedDestinationsFromAudienceAlphaOutput struct {
	value *ListSupportedDestinationsFromAudienceAlphaOutput
	isSet bool
}

func (v NullableListSupportedDestinationsFromAudienceAlphaOutput) Get() *ListSupportedDestinationsFromAudienceAlphaOutput {
	return v.value
}

func (v *NullableListSupportedDestinationsFromAudienceAlphaOutput) Set(
	val *ListSupportedDestinationsFromAudienceAlphaOutput,
) {
	v.value = val
	v.isSet = true
}

func (v NullableListSupportedDestinationsFromAudienceAlphaOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableListSupportedDestinationsFromAudienceAlphaOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSupportedDestinationsFromAudienceAlphaOutput(
	val *ListSupportedDestinationsFromAudienceAlphaOutput,
) *NullableListSupportedDestinationsFromAudienceAlphaOutput {
	return &NullableListSupportedDestinationsFromAudienceAlphaOutput{value: val, isSet: true}
}

func (v NullableListSupportedDestinationsFromAudienceAlphaOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSupportedDestinationsFromAudienceAlphaOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
